name: Deploy Frontend on Push
on:
  push:
    branches: [ Frontend ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files to FTP server
        uses: radenpioneer/astro-ftp-deploy@v0.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          directory: htdocs/ # The path to upload to, on your FTP server, relative to your FTP root. Must end with trailing slash. (optional)
          path: dist/. 
